language: node_js
node_js:
    - stable
before_install:
    - sudo apt-get install -y pv
before_script:
    - sudo cp mysql-custom.cnf /etc/mysql/conf.d/mysql-custom.cnf
    - sudo service mysql restart
    - node index.js > sql/import.sql
script:
    - mysql -e 'CREATE DATABASE app;'
    - mysql < sql/createUTF8.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
    - mysql < sql/drop.sql
    - mysql < sql/createUTF8mb4.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
    - mysql < sql/drop.sql
    - mysql < sql/createMetaKeyNotMB4.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
    - mysql < sql/drop.sql
    - sudo cp mysql-custom-innodb_large_prefix.cnf /etc/mysql/conf.d/mysql-custom.cnf
    - sudo service mysql restart
    - mysql < sql/createMetaKeyNotMB4.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
    - mysql < sql/drop.sql
    - mysql < sql/createUTF8mb4innodb_large_prefix.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
